//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace posk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoria_subcategoria
    {
        public int id { get; set; }
        public Nullable<int> categoria_id { get; set; }
        public Nullable<int> subcategoria_id { get; set; }
    
        public virtual categoria categoria { get; set; }
        public virtual subcategoria subcategoria { get; set; }
    }
}
