//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace posk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jornada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public jornada()
        {
            this.bodega_movimiento = new HashSet<bodega_movimiento>();
            this.cantidadesvendidas_jornada = new HashSet<cantidadesvendidas_jornada>();
            this.ventas_jornada = new HashSet<ventas_jornada>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> fecha_apertura { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
        public Nullable<bool> especial { get; set; }
        public string mensaje { get; set; }
        public Nullable<int> ingresos { get; set; }
        public Nullable<int> usuario_id { get; set; }
        public int caja_inicial_efectivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bodega_movimiento> bodega_movimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cantidadesvendidas_jornada> cantidadesvendidas_jornada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ventas_jornada> ventas_jornada { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
