//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace posk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidos_productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pedidos_productos()
        {
            this.pedidos_agregados = new HashSet<pedidos_agregados>();
            this.pedidos_preparaciones = new HashSet<pedidos_preparaciones>();
        }
    
        public int id { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<int> pedido_id { get; set; }
        public Nullable<int> producto_id { get; set; }
        public Nullable<bool> impreso { get; set; }
        public Nullable<decimal> impreso_cantidad { get; set; }
        public Nullable<int> promo_id { get; set; }
        public int precio { get; set; }
        public string nota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedidos_agregados> pedidos_agregados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedidos_preparaciones> pedidos_preparaciones { get; set; }
        public virtual promocione promocione { get; set; }
        public virtual pedido pedido { get; set; }
        public virtual producto producto { get; set; }
    }
}
