//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace posk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidos_agregados
    {
        public int id { get; set; }
        public Nullable<int> pedidos_productos_id { get; set; }
        public Nullable<int> agregado_uno_id { get; set; }
        public Nullable<int> agregado_dos_id { get; set; }
    
        public virtual pedidos_productos pedidos_productos { get; set; }
        public virtual agregado agregado { get; set; }
        public virtual agregado agregado1 { get; set; }
    }
}
