//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace posk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto_compra
    {
        public int id { get; set; }
        public int compra_id { get; set; }
        public int producto_id { get; set; }
        public decimal cantidad_disponible { get; set; }
        public Nullable<decimal> costo_unitario { get; set; }
        public Nullable<decimal> cantidad_compra { get; set; }
        public Nullable<bool> activa { get; set; }
    
        public virtual compra compra { get; set; }
        public virtual producto producto { get; set; }
    }
}
