//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace posk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class promocione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public promocione()
        {
            this.detalle_boleta = new HashSet<detalle_boleta>();
            this.pendientes = new HashSet<pendiente>();
            this.producto_promocion = new HashSet<producto_promocion>();
            this.ventas_jornada = new HashSet<ventas_jornada>();
            this.pedidos_productos = new HashSet<pedidos_productos>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> precio { get; set; }
        public string imagen { get; set; }
        public Nullable<int> subcategoria_id { get; set; }
        public Nullable<bool> favorito { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_boleta> detalle_boleta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pendiente> pendientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto_promocion> producto_promocion { get; set; }
        public virtual subcategoria subcategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ventas_jornada> ventas_jornada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedidos_productos> pedidos_productos { get; set; }
    }
}
