//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace posk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_producto_opcionales
    {
        public int id { get; set; }
        public int tipo_producto_id { get; set; }
        public int opcional_id { get; set; }
    
        public virtual opcionale opcionale { get; set; }
        public virtual tipo_producto tipo_producto { get; set; }
    }
}
