//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace posk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventas_jornada
    {
        public int id { get; set; }
        public Nullable<int> jornada_id { get; set; }
        public int cantidad { get; set; }
        public int cobro_extra { get; set; }
        public int detalle_boleta_id { get; set; }
        public string opcion { get; set; }
    
        public virtual detalle_boleta detalle_boleta { get; set; }
        public virtual jornada jornada { get; set; }
    }
}
